Bracket whole script with +-e. Remove debug messages.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -266,13 +266,13 @@ before_script:
 
 script:
 - |
+  set -e # Instead of trying to chain everything together with &&
+         # otherwise subsequent commands will swallow bad exit status.
   case "${TRAVIS_OS_NAME:-linux}" in
   linux)
     if [ "$CHECK_REUSE" = "YES" -o "$CHECK_REUSE" = "ONLY" ]; then
       echo "Calling reuse lint."
-      set -e  # because the if below swallows a bad exit status.
       reuse --suppress-deprecation lint
-      set +e
     fi
     if [ "$CHECK_REUSE" != "ONLY" -a "$CHECK_MKVK" != "ONLY" ]; then
       if [ "$WASM_BUILD" = "YES" ]; then
@@ -293,9 +293,7 @@ script:
     ;;
   esac
   if [ "$CHECK_MKVK" = "ONLY" ]; then
-    set -e  # instead of linking commands with &&.
     ci_scripts/check_mkvk.sh
-    set +e
   fi
   if [ "$DEPLOY_DOCS" = "YES" ]; then
     # Some files in the pyktx docs have an _ prefix so Jekyll will
@@ -303,6 +301,7 @@ script:
     # file says no Jekyll files here. Treat all as ordinary files.
     touch $BUILD_DIR/docs/html/.nojekyll
   fi
+  set +e
 
 # See if this helps with truncated logs.
 #after_script:
