Test different way of error handling.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -34,44 +34,44 @@ env:
     - VULKAN_INSTALL_DIR: "$HOME/VulkanSDK/$VULKAN_SDK_VER"
     - VULKAN_SDK: "$VULKAN_INSTALL_DIR/macOS"
     - WASM_BUILD: NO
-  jobs:
-    - CONFIGURATION=Debug PLATFORM=macOS ARCH=x86_64
-      FEATURE_DOC=OFF FEATURE_JNI=OFF FEATURE_LOADTESTS=ON FEATURE_TOOLS=ON
-      SUPPORT_SSE=ON SUPPORT_OPENCL=OFF
-    - CONFIGURATION=Release PLATFORM=macOS ARCH=x86_64
-      FEATURE_DOC=ON FEATURE_JNI=ON FEATURE_LOADTESTS=ON FEATURE_TOOLS=ON
-      SUPPORT_SSE=ON SUPPORT_OPENCL=OFF PACKAGE=YES
-    - CONFIGURATION=Release PLATFORM=macOS ARCH=arm64
-      FEATURE_DOC=ON FEATURE_JNI=ON FEATURE_LOADTESTS=ON FEATURE_TOOLS=ON
-      SUPPORT_SSE=ON SUPPORT_OPENCL=OFF PACKAGE=YES
-
-    - CONFIGURATION=Release PLATFORM=macOS ARCH=x86_64
-      FEATURE_DOC=ON FEATURE_JNI=OFF FEATURE_LOADTESTS=OFF FEATURE_TOOLS=OFF
-      SUPPORT_SSE=ON SUPPORT_OPENCL=ON
-    - CONFIGURATION=Release PLATFORM=macOS ARCH=arm64
-      FEATURE_DOC=ON FEATURE_JNI=OFF FEATURE_LOADTESTS=OFF FEATURE_TOOLS=OFF
-      SUPPORT_SSE=ON SUPPORT_OPENCL=ON
-
-    - CONFIGURATION=Release PLATFORM=macOS ARCH=x86_64
-      FEATURE_DOC=ON FEATURE_JNI=OFF FEATURE_LOADTESTS=OFF FEATURE_TOOLS=OFF
-      SUPPORT_SSE=OFF SUPPORT_OPENCL=ON
-    - CONFIGURATION=Release PLATFORM=macOS ARCH=arm64
-      FEATURE_DOC=ON FEATURE_JNI=OFF FEATURE_LOADTESTS=OFF FEATURE_TOOLS=OFF
-      SUPPORT_SSE=OFF SUPPORT_OPENCL=ON
-
-    - CONFIGURATION=Release PLATFORM=macOS ARCH=x86_64
-      FEATURE_DOC=ON FEATURE_JNI=OFF FEATURE_LOADTESTS=OFF FEATURE_TOOLS=OFF
-      SUPPORT_SSE=OFF SUPPORT_OPENCL=OFF
-    - CONFIGURATION=Release PLATFORM=macOS ARCH=arm64
-      FEATURE_DOC=ON FEATURE_JNI=OFF FEATURE_LOADTESTS=OFF FEATURE_TOOLS=OFF
-      SUPPORT_SSE=OFF SUPPORT_OPENCL=OFF
-
-    - CONFIGURATION=Debug PLATFORM=iOS
-      FEATURE_DOC=OFF FEATURE_JNI=OFF FEATURE_LOADTESTS=ON FEATURE_TOOLS=OFF
-      SUPPORT_SSE=OFF SUPPORT_OPENCL=OFF
-    - CONFIGURATION=Release PLATFORM=iOS
-      FEATURE_DOC=OFF FEATURE_JNI=OFF FEATURE_LOADTESTS=ON FEATURE_TOOLS=OFF
-      SUPPORT_SSE=OFF SUPPORT_OPENCL=OFF
+#  jobs:
+#    - CONFIGURATION=Debug PLATFORM=macOS ARCH=x86_64
+#      FEATURE_DOC=OFF FEATURE_JNI=OFF FEATURE_LOADTESTS=ON FEATURE_TOOLS=ON
+#      SUPPORT_SSE=ON SUPPORT_OPENCL=OFF
+#    - CONFIGURATION=Release PLATFORM=macOS ARCH=x86_64
+#      FEATURE_DOC=ON FEATURE_JNI=ON FEATURE_LOADTESTS=ON FEATURE_TOOLS=ON
+#      SUPPORT_SSE=ON SUPPORT_OPENCL=OFF PACKAGE=YES
+#    - CONFIGURATION=Release PLATFORM=macOS ARCH=arm64
+#      FEATURE_DOC=ON FEATURE_JNI=ON FEATURE_LOADTESTS=ON FEATURE_TOOLS=ON
+#      SUPPORT_SSE=ON SUPPORT_OPENCL=OFF PACKAGE=YES
+#
+#    - CONFIGURATION=Release PLATFORM=macOS ARCH=x86_64
+#      FEATURE_DOC=ON FEATURE_JNI=OFF FEATURE_LOADTESTS=OFF FEATURE_TOOLS=OFF
+#      SUPPORT_SSE=ON SUPPORT_OPENCL=ON
+#    - CONFIGURATION=Release PLATFORM=macOS ARCH=arm64
+#      FEATURE_DOC=ON FEATURE_JNI=OFF FEATURE_LOADTESTS=OFF FEATURE_TOOLS=OFF
+#      SUPPORT_SSE=ON SUPPORT_OPENCL=ON
+#
+#    - CONFIGURATION=Release PLATFORM=macOS ARCH=x86_64
+#      FEATURE_DOC=ON FEATURE_JNI=OFF FEATURE_LOADTESTS=OFF FEATURE_TOOLS=OFF
+#      SUPPORT_SSE=OFF SUPPORT_OPENCL=ON
+#    - CONFIGURATION=Release PLATFORM=macOS ARCH=arm64
+#      FEATURE_DOC=ON FEATURE_JNI=OFF FEATURE_LOADTESTS=OFF FEATURE_TOOLS=OFF
+#      SUPPORT_SSE=OFF SUPPORT_OPENCL=ON
+#
+#    - CONFIGURATION=Release PLATFORM=macOS ARCH=x86_64
+#      FEATURE_DOC=ON FEATURE_JNI=OFF FEATURE_LOADTESTS=OFF FEATURE_TOOLS=OFF
+#      SUPPORT_SSE=OFF SUPPORT_OPENCL=OFF
+#    - CONFIGURATION=Release PLATFORM=macOS ARCH=arm64
+#      FEATURE_DOC=ON FEATURE_JNI=OFF FEATURE_LOADTESTS=OFF FEATURE_TOOLS=OFF
+#      SUPPORT_SSE=OFF SUPPORT_OPENCL=OFF
+#
+#    - CONFIGURATION=Debug PLATFORM=iOS
+#      FEATURE_DOC=OFF FEATURE_JNI=OFF FEATURE_LOADTESTS=ON FEATURE_TOOLS=OFF
+#      SUPPORT_SSE=OFF SUPPORT_OPENCL=OFF
+#    - CONFIGURATION=Release PLATFORM=iOS
+#      FEATURE_DOC=OFF FEATURE_JNI=OFF FEATURE_LOADTESTS=ON FEATURE_TOOLS=OFF
+#      SUPPORT_SSE=OFF SUPPORT_OPENCL=OFF
 
 jobs:
   include:
@@ -168,7 +168,9 @@ install:
   case "${TRAVIS_OS_NAME:-linux}" in
   linux)
     if [ "$CHECK_REUSE" = "YES" -o "$CHECK_REUSE" = "ONLY" ]; then
+      set -e  # because the if below swallows a bad exit status.
       pip3 install reuse
+      set +e
     fi
     if [ "$CHECK_REUSE" != "ONLY" -a "$WASM_BUILD" != "YES" ]; then
       ./ci_scripts/install_linux.sh
@@ -199,11 +201,12 @@ script:
 - |
   case "${TRAVIS_OS_NAME:-linux}" in
   linux)
-    set -e  # because the 2nd if below swallows a bad exit status.
     echo "CHECK_REUSE = $CHECK_REUSE"
     if [ "$CHECK_REUSE" = "YES" -o "$CHECK_REUSE" = "ONLY" ]; then
       echo "Calling reuse lint."
+      set -e  # because the if below swallows a bad exit status.
       reuse lint
+      set +e
     fi
     if [ "$CHECK_REUSE" != "ONLY" ]; then
       if [ "$WASM_BUILD" = "YES" ]; then
