Don't download VulkanSDK & build shaderc when cache exists.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -81,13 +81,19 @@ install:
     sudo apt-get -qq update; sudo apt-get -qq install libvulkan1 libvulkan-dev &&
     sudo apt-get -qq update; sudo apt-get -qq install libassimp3v5 libassimp-dev &&
     pushd ../.. &&
-    wget -O vulkansdk-linux-x86_64-$VULKAN_SDK_VER.run https://sdk.lunarg.com/sdk/download/$VULKAN_SDK_VER/linux/vulkansdk-linux-x86_64-$VULKAN_SDK_VER.run?Human=true &&
-    chmod ugo+x *.run &&
-    ./*.run &&
-    cd VulkanSDK/$VULKAN_SDK_VER &&
-    source ./setup-env.sh &&
-    ./build_tools.sh --shaderc &&
-    echo "build_tools.sh exit status: " $?
+    if [ ! -d VulkanSDK ]; then
+      wget -O vulkansdk-linux-x86_64-$VULKAN_SDK_VER.run https://sdk.lunarg.com/sdk/download/$VULKAN_SDK_VER/linux/vulkansdk-linux-x86_64-$VULKAN_SDK_VER.run?Human=true &&
+      chmod ugo+x *.run &&
+      ./*.run &&
+      cd VulkanSDK/$VULKAN_SDK_VER &&
+      source ./setup-env.sh &&
+      ./build_tools.sh --shaderc &&
+      # This somwhow swallows a bogus error exit status of 1 from build_tools.sh
+      echo "build_tools.sh exit status: " $?;
+    else
+      cd VulkanSDK/$VULKAN_SDK_VER &&
+      source ./setup-env.sh;
+    fi &&
     popd
     ;;
   osx)
