Change mip level padding to match draft 18 rules. (#170)
* Validate mip padding as specified in KTX2 draft 18.

* Create & read files with KTX2 draft 18 mip padding.

* Regen all the reference ktx2 files.

Also contains the following:

* Use info from dfd instead of vkGetFormatSize.

* Create output file for each input file - bug fix in ktx2ktx2.

* Improve validation. Fixes #151. Fixes #152.

diff --git a/tests/ktx2check-tests b/tests/ktx2check-tests
--- a/tests/ktx2check-tests
+++ b/tests/ktx2check-tests
@@ -171,7 +171,7 @@ else
 fi
 
 numtests=$numtests+1
-output=$($ktx2check --quiet *.ktx2)
+output=$($ktx2check --quiet invalid_face_count.ktx2)
 if [ $? -eq 0 ]; then
     echo "Invalid face count not spotted."
     failed=$failed+1
@@ -184,6 +184,28 @@ else
     fi
 fi
 
+numtests=$numtests+1
+cd ../badktx2
+if $ktx2check incorrect_mip_layout_and_padding.ktx2 > /dev/null; then
+    echo "Invalid mip layout not spotted."
+    failed=$failed+1
+else
+    passed=$passed+1
+fi
+
+numtests=$numtests+1
+output=$($ktx2check --quiet incorrect_mip_layout_and_padding.ktx2)
+if [ $? -eq 0 ]; then
+    echo "Invalid mip layout not spotted."
+    failed=$failed+1
+else
+    if [ -z $output ]; then
+        passed=$passed+1
+    else
+        echo "Output written with --quiet."
+        failed=$failed+1
+    fi
+fi
 echo "Tests run: $numtests; passed: $passed; failed: $failed"
 if [ $failed -gt 0 ]; then
   exit 1;
