Support building of loadtest apps with locally installed dependencies (#799)
to allow building on Windows arm64 without adding more binaries to
`other_lib`.

* Rationalize include file search directories for appfwSDL, GLAppSDL
   and glloadtests.
* Set up to build loadtest apps for arm64 in Windows CI. Disabled
   because the Windows SDK chosen by CMake does not contain a
   needed library and I have yet to find a way to force selection of
   the latest SDK which does include it.
* Set up x86_64 macOS CI builds to use Brew-installed dependencies.

Other items emerged during this work.

* Fix Windows' loadtest apps to find their resources when run.
* Fix inability to debug libktx on Windows caused by both `ktx.exe`
  and `ktx.dll` trying to use `ktx.pdb`.
* Fix syntax error in tag selection in Actions .yml files.

diff --git a/.github/workflows/windows.yml b/.github/workflows/windows.yml
--- a/.github/workflows/windows.yml
+++ b/.github/workflows/windows.yml
@@ -15,8 +15,8 @@ on:
     # Also trigger on push of release tags to any branch. Useful
     # for testing release builds before merging to main.
     tags:
-      - 'v[0-9]+\.[0-9]+\.[0-9]+'
-      - 'v[0-9]+\.[0-9]+\.[0-9]+-*'
+      - 'v[0-9]+.[0-9]+.[0-9]+'
+      - 'v[0-9]+.[0-9]+.[0-9]+-*'
     paths-ignore:
       - .appveyor.yml
       - .travis.yml
@@ -65,7 +65,9 @@ jobs:
             toolset: CLangCL
             arch: arm64
             # No tests on arm64 since the host is x64 and can't run the
-            # built tests
+            # built tests. loadtests is OFF because CMake insists on
+            # choosing an older Windows SDK which is missing glu32.lib.
+            # Can set to OpenGL once issue is resolved.
             options: {
               config: 'Debug,Release',
               doc: ON, jni: ON, loadtests: OFF, tests: ON, tools: ON, tools_cts: ON,
@@ -120,9 +122,26 @@ jobs:
     - name: Install NSIS with large string support
       shell: bash
       run: |
-        stack exec -- wget -O nsis-3.08-strlen_8192.zip https://downloads.sourceforge.net/nsis/NSIS%203/3.08/nsis-3.08-strlen_8192.zip
-        7z x -aoa -o"/c/Program Files (x86)/NSIS" nsis-3.08-strlen_8192.zip
-        rm nsis-3.08-strlen_8192.zip
+        retryCount=4
+        success=0
+        for i in $(seq $retryCount) ; do
+            echo "Attempt no: $i"
+            stack exec -- wget -O nsis-3.08-strlen_8192.zip https://downloads.sourceforge.net/nsis/NSIS%203/3.08/nsis-3.08-strlen_8192.zip
+            if [[ $? -eq 0 ]] ; then
+                success=1
+                7z x -aoa -o"/c/Program Files (x86)/NSIS" nsis-3.08-strlen_8192.zip
+                rm nsis-3.08-strlen_8192.zip
+                echo "Installation successful."
+                break
+            else
+                echo "Installation failed. Retrying..."
+                sleep $(( 2*$i ))
+            fi
+        done
+        if (( ! $success )) ; then
+            echo "Installation failed after $retryCount attempts."
+            exit 1
+        fi
 
     - name: Force fetch provoking tag's annotation.
       # Work around https://github.com/actions/checkout/issues/290.
@@ -163,6 +182,15 @@ jobs:
           dotnet tool install --global AzureSignTool
           echo "CODE_SIGN_KEY_VAULT=Azure" >> $env:GITHUB_ENV
         }
+
+    - name: Install Dependencies for load tests on arm64
+      if: matrix.arch == 'arm64' && matrix.options.loadtests != 'OFF'
+      run: |
+        pushd $env:VCPKG_INSTALLATION_ROOT
+        ./vcpkg install SDL2:arm64-windows assimp:arm64-windows glew:arm64-windows
+        cat buildtrees\glew\install-arm64-windows-rel-out.log
+        popd
+        echo "CMAKE_TOOLCHAIN_FILE=$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake" >> $env:GITHUB_ENV
 
     - name: Install Dependencies
       # This script only installs what's needed by ON FEATUREs.
