Split workflow (#689)
* Split GitHub Actions workflow into separate workflows for Android, MinGW and Windows.

* Update README.md build badges for this and other recent changes.

* Add automatic retries for failed Doxygen install attempts.

diff --git a/.github/workflows/windows.yml b/.github/workflows/windows.yml
--- a/.github/workflows/windows.yml
+++ b/.github/workflows/windows.yml
@@ -1,26 +1,28 @@
 # Copyright 2015-2020 The Khronos Group Inc.
 # SPDX-License-Identifier: Apache-2.0
-name: KTX-Software CI
+name: KTX-Software Windows CI
 
+# Seems no way to avoid duplicating this on logic in each .yml file.
+# See https://github.com/actions/starter-workflows/issues/245.
 on:
-  # Trigger the workflow on pull request,
-  # but only for the master branch
+  # Trigger the workflow on a pull request,
   pull_request:
-    branchs:
-      - master
+
+  push:
+    # And on pushes to main, which will occur when a PR is merged.
+    branches:
+      - main
+    # Also trigger on push of release tags to any branch. Useful
+    # for testing release builds before merging to main.
+    tags:
+      - "v*.*.*"
     paths-ignore:
       - .appveyor.yml
       - .travis.yml
 
-  # Also trigger on push of release tags
-  push:
-    tags:
-      - "v*.*.*"
-
   # Allow manual trigger
   workflow_dispatch:
 
-#runs-on: windows-2019
 jobs:
   windows:
     strategy:
@@ -47,9 +49,6 @@ jobs:
            sse: ON, opencl: ON}
         ]
         include:
-#          - os: windows-latest
-#            generator: 'Visual Studio 17 2022'
-#            toolset: v143
           - os: windows-2019
             generator: 'Visual Studio 16 2019'
             toolset: v142
@@ -60,15 +59,6 @@ jobs:
               package: NO,
               sse: ON, opencl: OFF
             }
-#          - os: windows-latest
-#            generator: 'Visual Studio 17 2022'
-#            toolset: CLangCL
-#            platform: x64
-#            options: {
-#              config: 'Release',
-#              doc: ON, jni: OFF, loadtests: OFF, tests: ON, tools: ON,
-#              package: YES
-#            }
           - os: windows-latest
             generator: 'Visual Studio 17 2022'
             toolset: CLangCL
@@ -129,14 +119,32 @@ jobs:
       if: github.ref_type == 'tag'
       run: git fetch -f origin ${{ github.ref }}:${{ github.ref }}
 
-    # Need doxygen if docs are supposed to be built
-    # Use the pre-installed `choco`. Although it's v1 it works. Do not
-    # do `uses: crazy-max/ghaction-chocolatey@v2` because it suffers
-    # frequent failures due to Chocolatey attempts to blackmail you
-    # into purchasing a license. If this does fail, re-run the build.
+    # Need doxygen if docs are supposed to be built.
+    # Note this suffers frequent failures due to Chocolatey attempts
+    # to blackmail you into purchasing a license. Hence we retry a
+    # few times. If this still fails, re-run the build.
     - name: Install Doxygen
       if: matrix.options.doc == 'ON'
-      run: choco install doxygen.install
+      #run: choco install doxygen.install
+      run: |
+        $retryCount = 4
+        $success = $false
+        for ($i = 1; $i -le $retryCount; $i++) {
+            Write-Host "Attempt no: $i"
+            choco install doxygen.install --no-progress
+            if ($LASTEXITCODE -eq 0) {
+                $success = $true
+                Write-Host "Installation successful."
+                break
+            } else {
+                Write-Host "Installation failed. Retrying..."
+                Start-Sleep -Seconds (2*$i)
+            }
+        }
+        if (-not $success) {
+            Write-Host "Installation failed after $retryCount attempts."
+            exit 1
+        }
 
     - name: Install AzureSignTool
       id: install-ast
@@ -203,131 +211,6 @@ jobs:
         draft: true
         prerelease: true
         files: ${{env.BUILD_DIR}}/KTX-Software-*.exe*
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
-  mingw:
-    runs-on: windows-latest
-
-    steps:
-    - uses: actions/checkout@v3
-      with:
-        # Fetch all history to make sure tags are
-        # included (used for version creation)
-        fetch-depth: 0
-    #- uses: Honeybunch/setup-mingw@v3
-    - uses: egor-tensin/setup-mingw@v2
-      with:
-        platform: x64
-    - name: Force update provoking tag
-      # Work around https://github.com/actions/checkout/issues/290.
-      if: github.ref_type == 'tag'
-      run: git fetch -f origin ${{ github.ref }}:${{ github.ref }}
-    - name: Pull test images from Git LFS
-      run: git lfs pull --include=tests/srcimages,tests/testimages
-    - name: Install Ninja
-      run: choco install ninja
-    - name: Configure Mingw x64
-      run: cmake -B build -G "Ninja Multi-Config" -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++
-    - name: Build Mingw x64 Debug
-      run: cmake --build build --config Debug
-    - name: Build Mingw x64 Release
-      run: cmake --build build --config Release
-    - name: Test Mingw build
-      run: ctest --test-dir build -C Release
-    - name: Upload test log
-      if: ${{ failure() }}
-      run: ci_scripts/on_failure.ps1
-
-  linux:
-
-    runs-on: ubuntu-latest
-
-    steps:
-    - uses: actions/checkout@v3
-      with:
-        # Fetch all history to make sure tags are
-        # included (used for version creation)
-        fetch-depth: 0
-
-    - uses: nttld/setup-ndk@v1
-      id: setup-ndk
-      with:
-        ndk-version: r21e
-        add-to-path: false
-
-    - name: Force fetch provoking tag's annotation.
-      # Work around https://github.com/actions/checkout/issues/290.
-      if: github.ref_type == 'tag'
-      run: git fetch -f origin ${{ github.ref }}:${{ github.ref }}
-
-    - name: Install Ninja
-      run: sudo apt-get install -y ninja-build
-
-    - name: android_Debug_arm64-v8a
-      run: ./ci_scripts/build_android_debug.sh
-      env:
-        ANDROID_ABI: arm64-v8a
-        ANDROID_NDK: ${{ steps.setup-ndk.outputs.ndk-path }}
-        ASTC_ISA: "ISA_NEON=ON"
-        CONFIGURATION: Debug
-
-    - name: android_arm64-v8a
-      run: ./ci_scripts/build_android.sh
-      env:
-        ANDROID_ABI: arm64-v8a
-        ANDROID_NDK: ${{ steps.setup-ndk.outputs.ndk-path }}
-        ASTC_ISA: "ISA_NEON=ON"
-
-    # Android ABI x86 is obsolete
-    # and not supported by ARM ASTC encoder
-
-    # - name: android_x86
-    #   run: ./ci_scripts/build_android.sh
-    #   env:
-    #     ANDROID_ABI: x86
-    #     ANDROID_NDK: ${{ steps.setup-ndk.outputs.ndk-path }}
-
-    - name: android_x86_64
-      run: ./ci_scripts/build_android.sh
-      env:
-        ANDROID_ABI: x86_64
-        ANDROID_NDK: ${{ steps.setup-ndk.outputs.ndk-path }}
-
-    - name: get-version
-      id: ktx-version
-      run: |
-        KTX_VERSION=$(cat build-android-arm64-v8a/ktx.version)
-        echo "KTX_VERSION=$KTX_VERSION" >> $GITHUB_ENV
-
-    # Android artifact
-    # Zips the include and lib dirs installed for each architecture
-    # by the preceding steps and uploads the zip.
-    - name: upload artifact
-      id: upload-artifact
-      uses: actions/upload-artifact@v3
-      with:
-        name: KTX-Software-${{env.KTX_VERSION}}-Android
-        path: install-android
-
-    # Make an archive to be deployed.
-    # Although the preceding step made an archive, Actions helpfully :-(
-    # unarchives the files on download.
-    - name: Create zip for deployment.
-      if: github.event_name == 'push' && github.ref_type == 'tag'
-      run: |
-        zip_basename=KTX-Software-${KTX_VERSION}-Android
-        ln -s install-android $zip_basename
-        zip -r $zip_basename.zip $zip_basename
-        sha1sum $zip_basename.zip > $zip_basename.zip.sha1
-
-    - name: Upload To Release
-      uses: softprops/action-gh-release@v1
-      if: github.event_name == 'push' && github.ref_type == 'tag'
-      with:
-        draft: true
-        prerelease: true
-        files:  KTX-Software-${{env.KTX_VERSION}}-Android.zip*
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
