Convert NSIS retry script to Bash.

diff --git a/.github/workflows/windows.yml b/.github/workflows/windows.yml
--- a/.github/workflows/windows.yml
+++ b/.github/workflows/windows.yml
@@ -120,26 +120,26 @@ jobs:
     - name: Install NSIS with large string support
       shell: bash
       run: |
-        $retryCount = 4
-        $success = $false
-        for ($i = 1; $i -le $retryCount; $i++) {
-            Write-Host "Attempt no: $i"
+        retryCount=4
+        success=0
+        for i in $(seq $retryCount) ; do
+            echo "Attempt no: $i"
             stack exec -- wget -O nsis-3.08-strlen_8192.zip https://downloads.sourceforge.net/nsis/NSIS%203/3.08/nsis-3.08-strlen_8192.zip
-            if ($LASTEXITCODE -eq 0) {
-                $success = $true
+            if [[ $? -eq 0 ]] ; then
+                success=1
                 7z x -aoa -o"/c/Program Files (x86)/NSIS" nsis-3.08-strlen_8192.zip
                 rm nsis-3.08-strlen_8192.zip
-                Write-Host "Installation successful."
+                echo "Installation successful."
                 break
-            } else {
-                Write-Host "Installation failed. Retrying..."
-                Start-Sleep -Seconds (2*$i)
-            }
-        }
-        if (-not $success) {
-            Write-Host "Installation failed after $retryCount attempts."
+            else
+                echo "Installation failed. Retrying..."
+                sleep $(( 2*$i ))
+            fi
+        done
+        if (( ! $success )) ; then
+            echo "Installation failed after $retryCount attempts."
             exit 1
-        }
+        fi
 
     - name: Force fetch provoking tag's annotation.
       # Work around https://github.com/actions/checkout/issues/290.
